import { Inter } from "next/font/google";
import "./globals.css";
import ModalHandler from "@/app/components/ModalHandler.jsx";
import Header from "./components/Header.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalHandler />
        <Header />
        {children}
      </body>
    </html>
  );
}
