import "./globals.css";
import ModalHandler from "@/app/components/ModalHandler.jsx";
import Header from "./components/Header.jsx";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils.js";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ModalHandler />
        <Header />
        {children}
      </body>
    </html>
  );
}
